services:
  your-service:
    # Required: Path to the docker-compose.yml file of the service
    path: /Users/ubuntu/your-service/docker-compose.yml
    # Optional: If you want to update all containers in the service, you can leave out the containers key.
    containers:
      - website
      - backend
# Required: A random string to secure the API
apiKey: randomString
# Optional: The number of images to keep for each container. This can be used to roll back to a previous version.
numberOfImagesToKeep: 2